### ISSUE TITLE
GLOB_BRACE breaks non-GNU systems

### ISSUE THREAD

**Issue by konstantinj** [mamuz/phalcon-application#1]
Hi,
when using this e.g. with alpine linux this error will raise:

> "NOTICE: PHP message: PHP Notice:  Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' in /var/www/vendor/mamuz/phalcon-application/src/Application/Service/Config.php on line 58"
> Could be solved with a fallback function like https://github.com/zendframework/zend-stdlib/blob/master/src/Glob.php.

**Comment by mamuz** [comment]
It's fixed and will be released soon.
Thanks to @konstantinj for that issue.
